development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: test_san_development
  username: root
  password: root

# test:
#   <<: *default
#   database: test_san_test

# production:
#   <<: *default
#   database: test_san_production
#   username: active-admin-test
#   password: <%= ENV['ACTIVE-ADMIN-TEST_DATABASE_PASSWORD'] %>
